version: "2"
services:
  mongo:
    image: mongo
    container_name: nfl-player-data-mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - data-volume:/data/db

  nfl-player-data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfl-player-data
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    restart:
      always
    environment:
      VIRTUAL_HOST: nfl-player-data.hard-g.com
      LETSENCRYPT_HOST: nfl-player-data.hard-g.com
      LETSENCRYPT_EMAIL: brent.rager@gmail.com

volumes:
  data-volume:

networks:
  default:
    external:
      name: nginx-proxy
